[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
if = "has('python3')"
hook_add = '''
  nmap <silent> <C-u><C-f> :<C-u>Denite file_rec<CR>
  nmap <silent> <C-u><C-g> :<C-u>Denite grep<CR>
  nmap <silent> <C-u><C-h> :<C-u>DeniteCursorWord grep<CR>
'''
hook_post_source = '''
	call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
  call denite#custom#var('grep', 'command', ['ag'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', [])
  call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])

  call denite#custom#map('insert', '<C-j>', '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', '<C-k>', '<denite:move_to_previous_line>', 'noremap') 
 
  call denite#custom#option('default', 'prompt', '>')
'''
